### ISSUE TITLE
Services' type

### ISSUE THREAD

**Issue by dogoepp** [ros-drivers/phidgets_drivers#23]
Hello,

I realise now that my approach to services for IL, in #22 might not be the best.
Wouldn't it be better to define a single service with two parameters : id of the output (int) and state (bool) ?

**Comment by mintar** [comment]
Hmmm... both approaches have their merits.

Single service:

* simplifies the calling code: you only need one service client if you want to set multiple outputs

One service per output:

* you can remap the service name to something semantically meaningful
* doesn't need a custom service definition

But overall I agree that having a single service would probably be better. If you want to do the change, let's do it now before I make a new release; I try to keep the API stable, but since we only introduced these services recently I think nobody (except you) is already using them.

**Comment by dogoepp** [comment]
I agree with you. Here is one proposal (#24). However, it allows for only one output to be set at a time. I can change it so that any number of outputs can be "simultaneously" set.
